spring:
  application:
    name: SpringToDo
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    root: info
    org.springframework.jdbc.core: debug
