spring:
  application:
    name: SpringToDo
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  cache:
    type: redis

logging:
  level:
    root: info
    org.springframework.jdbc.core: debug
